name: tuangechezs
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  talkingdata_appanalytics_plugin:
    path: ./appanalytics
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  dio: ^3.0.4
  fluttertoast: ^3.1.3
  toast: ^0.1.5
  shared_preferences: ^0.5.6+1
  flutter_screenutil: ^0.5.3
  permission_handler: ^4.0.0
  provider: ^3.2.0
  flutter_swiper: ^1.1.6
  flutter_cupertino_date_picker: ^1.0.12
  fluwx: ^1.2.0 
  image_picker: ^0.6.3+1
  webview_flutter: ^0.3.16
  photo_view: ^0.9.2
  url_launcher: ^5.4.1
  path: ^1.6.4
  path_provider: ^1.4.0
  okhttp_kit: ^1.0.0
  fake_weibo: ^0.2.4
  image_gallery_saver: ^1.2.2
  video_player: ^0.10.5
  chewie: ^0.9.8+1
  cached_network_image: ^2.2.0+1
  flutter_tencentplayer: ^0.6.0
  screen: 0.0.5
  flutter_forbidshot: 0.0.2
  event_bus: ^1.1.0
  city_pickers: ^0.1.29
  flutter_easyrefresh: ^2.0.4
  flutter_html: ^0.11.0
  # flutter_qq: ^0.0.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/login.png
    - images/2.0x/login.png
    - images/3.0x/login.png
    - images/phone.png
    - images/2.0x/phone.png
    - images/3.0x/phone.png
    - images/mobile.png
    - images/2.0x/mobile.png
    - images/3.0x/mobile.png
    - images/agreement.png
    - images/2.0x/agreement.png
    - images/3.0x/agreement.png
    - images/agreementselect.png
    - images/2.0x/agreementselect.png
    - images/3.0x/agreementselect.png
    - images/name.png
    - images/2.0x/name.png
    - images/3.0x/name.png
    - images/idcard.png
    - images/2.0x/idcard.png
    - images/3.0x/idcard.png
    - images/extension.png
    - images/2.0x/extension.png
    - images/3.0x/extension.png
    - images/extensionselect.png
    - images/2.0x/extensionselect.png
    - images/3.0x/extensionselect.png
    - images/order.png
    - images/2.0x/order.png
    - images/3.0x/order.png
    - images/orderselect.png
    - images/2.0x/orderselect.png
    - images/3.0x/orderselect.png
    - images/my.png
    - images/2.0x/my.png
    - images/3.0x/my.png
    - images/myselect.png
    - images/2.0x/myselect.png
    - images/3.0x/myselect.png
    - images/homebg.png
    - images/2.0x/homebg.png
    - images/3.0x/homebg.png
    - images/card.png
    - images/2.0x/card.png
    - images/3.0x/card.png
    - images/rightmore.png
    - images/2.0x/rightmore.png
    - images/3.0x/rightmore.png
    - images/loginnew.png
    - images/2.0x/loginnew.png
    - images/3.0x/loginnew.png
    - images/back.png
    - images/2.0x/back.png
    - images/3.0x/back.png
    - images/myright.png
    - images/2.0x/myright.png
    - images/3.0x/myright.png
    - images/myicon.png
    - images/2.0x/myicon.png
    - images/3.0x/myicon.png
    - images/money.png
    - images/2.0x/money.png
    - images/3.0x/money.png
    - images/select.png
    - images/2.0x/select.png
    - images/3.0x/select.png
    - images/cardbg.png
    - images/2.0x/cardbg.png
    - images/3.0x/cardbg.png
    - images/qrcode.png
    - images/2.0x/qrcode.png
    - images/3.0x/qrcode.png
    - images/contact.png
    - images/2.0x/contact.png
    - images/3.0x/contact.png
    - images/company.png
    - images/2.0x/company.png
    - images/3.0x/company.png
    - images/address.png
    - images/2.0x/address.png
    - images/3.0x/address.png
    - images/broker.png
    - images/2.0x/broker.png
    - images/3.0x/broker.png
    - images/selectlogin.png
    - images/2.0x/selectlogin.png
    - images/3.0x/selectlogin.png
    - images/agent.png
    - images/2.0x/agent.png
    - images/3.0x/agent.png
    - images/brokerselect.png
    - images/2.0x/brokerselect.png
    - images/3.0x/brokerselect.png
    - images/agentselect.png
    - images/2.0x/agentselect.png
    - images/3.0x/agentselect.png
    - images/unselect.png
    - images/2.0x/unselect.png
    - images/3.0x/unselect.png
    - images/selectposter.png
    - images/2.0x/selectposter.png
    - images/3.0x/selectposter.png
    - images/share.png
    - images/2.0x/share.png
    - images/3.0x/share.png
    - images/nofind.png
    - images/2.0x/nofind.png
    - images/3.0x/nofind.png
    - images/wechat.png
    - images/2.0x/wechat.png
    - images/3.0x/wechat.png
    - images/timeline.png
    - images/2.0x/timeline.png
    - images/3.0x/timeline.png
    - images/weibo.png
    - images/2.0x/weibo.png
    - images/3.0x/weibo.png
    - images/carsbg.png
    - images/2.0x/carsbg.png
    - images/3.0x/carsbg.png
    - images/agentbg.png
    - images/2.0x/agentbg.png
    - images/3.0x/agentbg.png
    - images/wechatnum.png
    - images/2.0x/wechatnum.png
    - images/3.0x/wechatnum.png
    - images/play.png
    - images/2.0x/play.png
    - images/3.0x/play.png
    - images/sharevideo.png
    - images/2.0x/sharevideo.png
    - images/3.0x/sharevideo.png
    - images/invitation.png
    - images/2.0x/invitation.png
    - images/3.0x/invitation.png
    - images/editer.png
    - images/2.0x/editer.png
    - images/3.0x/editer.png
    - images/3.0x/editer.png
    - images/3.0x/editer.png
    - images/exchange.png
    - images/2.0x/exchange.png
    - images/3.0x/exchange.png
    - images/integral.png
    - images/2.0x/integral.png
    - images/3.0x/integral.png
    - images/pointbg.png
    - images/2.0x/pointbg.png
    - images/3.0x/pointbg.png
    - images/rightmy.png
    - images/2.0x/rightmy.png
    - images/3.0x/rightmy.png
    - images/searchnew.png
    - images/2.0x/searchnew.png
    - images/3.0x/searchnew.png
    - images/coupon.png
    - images/2.0x/coupon.png
    - images/3.0x/coupon.png
    - images/upper.png
    - images/2.0x/upper.png
    - images/3.0x/upper.png
    - images/lower.png
    - images/2.0x/lower.png
    - images/3.0x/lower.png
    - images/icon_back.png
    - images/place_nodata.png
    - images/player_lock.png
    - images/player_pause.png
    - images/player_play.png
    - images/player_progress_img.png
    - images/player_rotate.png
    - images/player_unlock.png
    - images/video_loading.png
    - images/full_screen_on.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
